apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: acm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: saidaghribi/my-app-acm:frontend
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      imagePullSecrets:
        - name: regcred
