apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: acm
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32402
  type: NodePort
