apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  namespace: acm
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
      - name: reporting
        image: saidaghribi/my-app-acm:reporting-service
        ports:
        - containerPort: 8099
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_CLOUD_CONSUL_HOST
          value: "consul-server.acm.svc.cluster.local"
        - name: SPRING_CLOUD_CONSUL_PORT
          value: "8500"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      imagePullSecrets:
        - name: regcred-backend
